"""devcontainerのRリファレンス実装（R本体・Rパッケージ）の更新を確認する。

DependabotはCRAN（Rパッケージ）を扱えないため、`.devcontainer/Dockerfile`で
`remotes::install_version()`によりピン留めしたRパッケージの新版と、R本体の新版を
このスクリプトで検出する。`check_r_updates.yml`から定期実行され、差分があれば
Issueの本文に使うMarkdownを書き出す。

- Rパッケージ: Dockerfileのピン留めバージョン vs CRAN（`src/contrib/PACKAGES`）の
  最新版。
- R本体: フィクスチャJSONの`_meta.r_version`（凍結値の生成に使ったR）のうち最大の
  版 vs CRAN公式Debian向けAPTリポジトリ（`bookworm-cran40`）の`r-base`最新版。
  R本体はAPT経由で導入しており版を固定できない（索引に最新版しか載らない）ため、
  「凍結値を生成した時点のR」を基準にする。

標準ライブラリのみで動く（Rのインストール不要）。標準出力には要約のみを出す。

使用例（リポジトリルートから）:
    python .github/scripts/check_r_updates.py --output report.md
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
_DOCKERFILE = _REPO_ROOT / ".devcontainer" / "Dockerfile"
_FIXTURES_DIR = _REPO_ROOT / "tests" / "fixtures" / "benchmarks"

_CRAN_PACKAGES_URL = "https://cloud.r-project.org/src/contrib/PACKAGES"
_CRAN_APT_PACKAGES_URL = (
    "https://cloud.r-project.org/bin/linux/debian/bookworm-cran40/Packages"
)

# `remotes::install_version("pkg", version = "x.y", ...)`（Dockerfileの書式）
_PIN_RE = re.compile(
    r'install_version\(\s*"(?P<pkg>[^"]+)"\s*,\s*version\s*=\s*"(?P<ver>[^"]+)"'
)
# Debianのr-baseバージョン（例: `4.5.3-1~bookwormcran.0`）からR本体の版を取る
_DEBIAN_R_VERSION_RE = re.compile(r"^(?:\d+:)?(?P<ver>\d+(?:\.\d+)*)-")


def parse_pinned_packages(dockerfile_text: str) -> dict[str, str]:
    """Dockerfileからピン留めされたRパッケージ名→バージョンを取り出す。"""
    return {m["pkg"]: m["ver"] for m in _PIN_RE.finditer(dockerfile_text)}


def _parse_debcontrol_stanzas(text: str) -> list[dict[str, str]]:
    """PACKAGES / Debian Packages形式（空行区切りの`Key: value`）を解析する。"""
    stanzas = []
    for block in text.split("\n\n"):
        fields = {}
        for line in block.splitlines():
            if line[:1].isspace() or ":" not in line:
                continue
            key, _, value = line.partition(":")
            fields[key.strip()] = value.strip()
        if fields:
            stanzas.append(fields)
    return stanzas


def parse_cran_versions(packages_text: str) -> dict[str, str]:
    """CRANの`PACKAGES`からパッケージ名→最新バージョンを取り出す。"""
    return {
        s["Package"]: s["Version"]
        for s in _parse_debcontrol_stanzas(packages_text)
        if "Package" in s and "Version" in s
    }


def parse_apt_r_base_version(apt_packages_text: str) -> str | None:
    """APT索引から`r-base`の最新のR本体バージョン（例: `4.5.3`）を取り出す。"""
    for stanza in _parse_debcontrol_stanzas(apt_packages_text):
        if stanza.get("Package") == "r-base":
            m = _DEBIAN_R_VERSION_RE.match(stanza.get("Version", ""))
            return m["ver"] if m else None
    return None


def _version_key(version: str) -> tuple[int, ...]:
    """Rの版比較用キー。Rでは`-`と`.`は同じ区切り（`0.6.8`＝`0.6-8`）。"""
    return tuple(int(p) for p in re.split(r"[.-]", version) if p.isdigit())


def fixture_r_version(fixtures_dir: Path) -> str | None:
    """フィクスチャJSONの`_meta.r_version`のうち最大の版を返す。"""
    versions = set()
    for path in sorted(fixtures_dir.glob("*.json")):
        meta = json.loads(path.read_text(encoding="utf-8")).get("_meta", {})
        if isinstance(meta, dict) and isinstance(meta.get("r_version"), str):
            versions.add(meta["r_version"])
    return max(versions, key=_version_key) if versions else None


def _fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=60) as resp:
        return resp.read().decode("utf-8")


def render_report(
    outdated: dict[str, tuple[str, str]],
    missing: list[str],
    r_base: tuple[str, str] | None,
) -> str:
    """Issue本文（英語・公開リポジトリのため）のMarkdownを組み立てる。"""
    lines = [
        (
            "Automatically generated by the `Check R updates` workflow "
            "(`.github/workflows/check_r_updates.yml`). This issue is "
            "updated on every run and closed automatically once everything "
            "is up to date."
        ),
        "",
    ]
    if outdated:
        lines += [
            "## R packages pinned in `.devcontainer/Dockerfile`",
            "",
            "| Package | Pinned | CRAN latest |",
            "|---|---|---|",
        ]
        lines += [
            f"| `{pkg}` | {pinned} | {latest} |"
            for pkg, (pinned, latest) in sorted(outdated.items())
        ]
        lines.append("")
    if missing:
        names = ", ".join(f"`{p}`" for p in sorted(missing))
        lines += [
            "## Pinned packages not found on CRAN",
            "",
            f"Archived or renamed? Check these manually: {names}",
            "",
        ]
    if r_base:
        lines += [
            "## R itself",
            "",
            (
                f"The frozen fixtures were generated with R **{r_base[0]}** "
                "(`_meta.r_version`), but the CRAN Debian repository "
                f"(`bookworm-cran40`) now provides R **{r_base[1]}**."
            ),
            "",
        ]
    lines += [
        "## How to update",
        "",
        (
            "1. Bump the versions in `.devcontainer/Dockerfile` "
            "(R packages are pinned with `remotes::install_version()`)."
        ),
        (
            "2. Rebuild the devcontainer, then regenerate the fixtures with "
            "`python -m benchmark.regenerate_all --fixtures-only`."
        ),
        (
            "3. Review the fixture diffs and run `pytest tests`. Major "
            "version bumps may change numerical results, so do not merge "
            "blindly."
        ),
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--output",
        type=Path,
        help="更新があるときにIssue本文のMarkdownを書き出すパス",
    )
    args = parser.parse_args()

    pinned = parse_pinned_packages(_DOCKERFILE.read_text(encoding="utf-8"))
    if not pinned:
        print("ERROR: no pinned R packages found in Dockerfile")
        return 2
    cran = parse_cran_versions(_fetch(_CRAN_PACKAGES_URL))

    outdated = {
        pkg: (ver, cran[pkg])
        for pkg, ver in pinned.items()
        if pkg in cran and _version_key(cran[pkg]) != _version_key(ver)
    }
    missing = [pkg for pkg in pinned if pkg not in cran]

    r_base = None
    fixture_r = fixture_r_version(_FIXTURES_DIR)
    latest_r = parse_apt_r_base_version(_fetch(_CRAN_APT_PACKAGES_URL))
    if (
        fixture_r
        and latest_r
        and _version_key(fixture_r) != _version_key(latest_r)
    ):
        r_base = (fixture_r, latest_r)

    print(
        f"pinned={len(pinned)} outdated={len(outdated)} "
        f"missing={len(missing)} r_base_outdated={r_base is not None}"
    )
    for pkg, (ver, latest) in sorted(outdated.items()):
        print(f"  {pkg}: {ver} -> {latest}")
    if r_base:
        print(f"  R: {r_base[0]} -> {r_base[1]}")

    if outdated or missing or r_base:
        if args.output:
            args.output.write_text(
                render_report(outdated, missing, r_base), encoding="utf-8"
            )
            print(f"report written: {args.output}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
